
def task1():
    try:
        answer = int(input("Enter an int:  "))
    except Exception as e:
        print(e)

task1()



